const team1 = {
  "starters": [
    {
      "name": "Dexter Fowler",
      "image": "images/sabina.png",
      "at_bats": 456,
      "total_hits": 126,
      "doubles": 25,
      "triples": 7,
      "home_runs": 13,
      "walks": 79,
      "hit_by_pitch": 11,
      "sacrifice_hits": 1,
      "sacrifice_flies": 4,
      "intentional_walks": 0
    },
    {
      "name": "Kris Bryant",
      "image": "images/sabina.png",
      "at_bats": 603,
      "total_hits": 176,
      "doubles": 35,
      "triples": 3,
      "home_runs": 39,
      "walks": 75,
      "hit_by_pitch": 18,
      "sacrifice_hits": 0,
      "sacrifice_flies": 3,
      "intentional_walks": 5
    },
    {
      "name": "Anthony Rizzo",
      "image": "images/sabina.png",
      "at_bats": 583,
      "total_hits": 170,
      "doubles": 43,
      "triples": 4,
      "home_runs": 32,
      "walks": 74,
      "hit_by_pitch": 16,
      "sacrifice_hits": 0,
      "sacrifice_flies": 3,
      "intentional_walks": 8
    },
    {
      "name": "Ben Zobrist",
      "image": "images/sabina.png",
      "at_bats": 523,
      "total_hits": 142,
      "doubles": 31,
      "triples": 3,
      "home_runs": 18,
      "walks": 96,
      "hit_by_pitch": 4,
      "sacrifice_hits": 4,
      "sacrifice_flies": 4,
      "intentional_walks": 6
    },
    {
      "name": "Addison Russell",
      "image": "images/sabina.png",
      "at_bats": 525,
      "total_hits": 125,
      "doubles": 25,
      "triples": 3,
      "home_runs": 21,
      "walks": 55,
      "hit_by_pitch": 12,
      "sacrifice_hits": 0,
      "sacrifice_flies": 6,
      "intentional_walks": 6
    },
    {
      "name": "Jorge Soler",
      "image": "images/sabina.png",
      "at_bats": 227,
      "total_hits": 54,
      "doubles": 9,
      "triples": 0,
      "home_runs": 12,
      "walks": 31,
      "hit_by_pitch": 3,
      "sacrifice_hits": 0,
      "sacrifice_flies": 3,
      "intentional_walks": 0
    },
    {
      "name": "Jason Heyward",
      "image": "images/sabina.png",
      "at_bats": 530,
      "total_hits": 122,
      "doubles": 27,
      "triples": 1,
      "home_runs": 7,
      "walks": 54,
      "hit_by_pitch": 5,
      "sacrifice_hits": 1,
      "sacrifice_flies": 2,
      "intentional_walks": 0
    },
    {
      "name": "Miguel Montero",
      "image": "images/sabina.png",
      "at_bats": 241,
      "total_hits": 52,
      "doubles": 8,
      "triples": 1,
      "home_runs": 8,
      "walks": 38,
      "hit_by_pitch": 3,
      "sacrifice_hits": 0,
      "sacrifice_flies": 2,
      "intentional_walks": 5
    },
    {
      "name": "Jon Lester",
      "image": "images/sabina.png",
      "at_bats": 59,
      "total_hits": 6,
      "doubles": 3,
      "triples": 0,
      "home_runs": 0,
      "walks": 6,
      "hit_by_pitch": 0,
      "sacrifice_hits": 10,
      "sacrifice_flies": 0,
      "intentional_walks": 0
    }
  ],
  "bench": [ ]
};
